#!/bin/bash
. `dirname $0`/tools_env
[ -f `dirname $0`/custom_tools_env ] && . `dirname $0`/custom_tools_env

exec ${ERL_DIR}erl \
    -pa $SERVER_EBIN_ROOT \
    -args_file $VMARGS_PATH \
    -name $SCRIPT_NAME$$@127.0.0.1 \
    -boot start_clean \
    -s gs_rel db_update \
    -s init stop \
    -noshell \
    -extra  "$@"
