#!/bin/sh

. `dirname $0`/tools_env
[ -f `dirname $0`/custom_tools_env ] && . `dirname $0`/custom_tools_env

exec ${ERL_DIR}erl \
    -pa $SERVER_EBIN_ROOT \
    -args_file $VMARGS_PATH \
    -name $SCRIPT_NAME$$@127.0.0.1 \
    -config $SERVER_HOME/sh/db_disc_1/sys.config \
    -boot start_clean \
    -s data_module_ctl \
    -extra  "$@"
