#!/bin/sh

. `dirname $0`/tools_env
[ -f `dirname $0`/custom_tools_env ] && . `dirname $0`/custom_tools_env

${ERL_DIR}erl \
    -pa $SERVER_EBIN_ROOT \
    -args_file $VMARGS_PATH \
    -name $SCRIPT_NAME$$@127.0.0.1 \
    -boot start_clean \
    -s generate_all_record  start\
    -s init stop

${ERL_DIR}erlc +debug_info -o  $SERVER_HOME/ebin/ -I$SERVER_HOME/include -I$SERVER_HOME/deps $SERVER_HOME/src/tools/all_record.erl


