#!/usr/bin/env escript
%% -*- erlang -*-
%%! -sasl errlog_type error -noshell

main ([File]) ->
    %% File "../proto/pb_10.proto"
    code:add_patha("./deps/protobuffs/ebin/"),
    protobuffs_compile:generate_source(
      File, [{imports_dir, ["./subgit/p02_proto/"]},
             {output_src_dir, "./src/protocol/"},
             {output_include_dir, "./include/"}]);

main (_) ->
  io:format ("usage: ~s <protofile>~n",
             [filename:basename (escript:script_name())]),
  halt (1).

